### ISSUE TITLE
Hiding skipped tests

### ISSUE THREAD

**Issue by NonInspirationalName** [AArnott/Xunit.SkippableFact#13]
Is it possible to completely hide skipped tests? So not passed, not failed, and not skipped?

In my case, I have created a abstract base test class which has a theory on various possible events that can occur, and will test a certain interface. Then I create derived test classes that test a certain implementation. The theory methods in the base class are automatically run for the derived classes as well. However, not all events specified in the inline data have to be supported by the implementation. The base class can detect this, and skips the test. All good so far.

However, it will now show as having skipped tests, which to me feels like it -should- run at some time. For example, in my integrated build pipeline I would prefer not to see skipped tests. However in this case, these tests will never run and thus will always show as being skipped.

Is there a way to completely hide these skipped tests? It would be great if we can somehow indicate this behavior on the SkippableTheory. Preferably I would not even see them in the runner output.

My previous implementation didn't use SkippableTheories, and simply made the test PASS. Which was also not too great, as then I get a lot of passes but I can not see which tests actually ran for the interface implementation.

Any help/insight is appreciated

**Comment by AArnott** [comment]
> Is it possible to completely hide skipped tests? So not passed, not failed, and not skipped?

No. For a test to be skipped, it had to be discovered. And the test list comes from discovery, not from test results.

For your requirement you'd need a custom test discovery attribute. An alternative to `[Fact]` or `[Theory]` whereby you can enumerate the test cases, filter out the ones that you want to "skip", and only return the remaining ones to the discovery system. You couldn't rely on running the test as part of this applicability check since this is just in the discovery phase. Given this, your discoverer would be custom for just your problem space, and thus I can't imagine at present how xunit.skippablefact could make it easier than what xunit already does itself.
