### ISSUE TITLE
Skip resulted in a fail with SkipException when Xunit.DependencyInjection is also referenced

### ISSUE THREAD

**Issue by datvm** [AArnott/Xunit.SkippableFact#25]
Whenever I put a skip, the result is a failed due to `SkipException`:

```
    [SkippableFact]
    public void Test2()
    {
        Skip.If(true);
    }

    [SkippableFact]
    public async Task Test()
    {
        Skip.If(true);
    }
```

![image](https://user-images.githubusercontent.com/6388546/140973238-74753bd4-6620-4a81-8af4-bf357c8d016a.png)

Did I miss something? On .NET 6 with VS2022

**Comment by AArnott** [comment]
It works for me. Does the attached work for you?

[TestProject1.zip](https://github.com/AArnott/Xunit.SkippableFact/files/7507122/TestProject1.zip)

**Comment by datvm** [comment]
Thanks seem like it's a conflict with [`Xunit.DependencyInjection`](https://github.com/pengweiqhca/Xunit.DependencyInjection). I could run the project you attached without problem, but as soon as I add `Xunit.DependencyInjection` package and `Startup.cs` class, same problem arises.

Do you know why there is this problem? Any workaround I can add? Thanks!

**Comment by AArnott** [comment]
Based on that project's readme:

> Use Microsoft.Extensions.DependencyInjection to resolve xUnit test cases.

I'm *guessing* that it takes over discovery of test methods, and therefore hijacks Xunit.SkippableFact's own handling of its own attribute. In doing so, it wouldn't know that the exception that the `Skip.If` method throws should be interpreted as a skip instead of a failed test.

I guess there's nothing for this repo to fix. I suggest you file an issue with the DI repo and see what they can do to avoid hijacking our attribute.

**Comment by datvm** [comment]
Ah yes, I forgot to search the other way around! There was [an issue](https://github.com/pengweiqhca/Xunit.DependencyInjection/issues/46) there with solution as well. Thank you so much for your time.
